version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./WWW:/var/www/html/WWW
    environment:
      - DATABASE_URL=mysql://db_user:db_password@db/db_name
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
