version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./WWW:/var/www/html/WWW
    environment:
      DATABASE_URL: "mysql://newuser:password@db/iis_db"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: iis_db
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
